### PR TITLE
Enable homu notifications

### PR DESCRIPTION
**Pull request by metajack**

### CODE REVIEW

**Comment by edunham** [comment]
Is excluding the master branch specific to rust-png workflow? Stylistically, I'd prefer either including master or documenting in the README why it's excluded. 

Also, should Homu be checking the "AppVeyor" build at all, since that's also enabled on the repo?

**Comment by metajack** [comment]
@edunham appveyor always fails. It's part of @Manishearth's windows work I believe and doesn't currently block things.

As for excluding master, see https://github.com/servo/saltfs/issues/59

**Comment by edunham** [comment]
Thanks for the link -- I updated the saltfs wiki page on it. 

r+

**Comment by Manishearth** [comment]
Turned off appveyor; I was just testing it out.

**Pull request merged**
