### PR TITLE
Add to_vec function for writing PNG data to a Vec<u8>.

### PR DESCRIPTION
**Pull request by jgraham**
This mostly copies the implementation of store_png, and could
probably be refactored to share more code in the future.

### CODE REVIEW

**Comment by metajack** [comment]
Can you add a test for this? I figured it would call to_vec and then verify the first bytes were the PNG magic bytes and that the total length was the expected one.

Otherwise, looks fine.

**Comment by jgraham** [comment]
This is rebased  onto master, but with the tests in a separate commit, because they won't trivially backport to the current servo branch (but the actual functionality will).

**Comment by metajack** [comment]
Squash and r=me.

**Comment by metajack** [comment]
Or are you saying you want to leave the tests in their own commit? If so, maybe change the commit message to not have fixup! in it?

**Comment by jgraham** [comment]
I'm happy to squash, but unless the rust upgrade is about to land it would be useful to create a servo branch with 16a9dba cherry-picked on top of the current servo commit.

**Comment by metajack** [comment]
Seems reasonable then. Just change the commit message to 'Add tests for to_vec.' and I'll merge this.

**Pull request merged**
